name: Node CI

on: [push]

jobs:
  build-lint-and-test:
    name: Build, lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install (ci)
        run: npm ci
      - name: Build
        run: npm build
      - name: Lint
        run: npm run lint
      - name: Unit tests
        run: npm test
